language: go
go:
  - 1.4
  - tip

services:
 - mysql
 - postgres
 - sqlite3
 - mongodb

before_script:
 - go get github.com/lib/pq
 - go get github.com/mattn/go-sqlite3
 - go get golang.org/x/tools/cmd/cover
 - go get github.com/ziutek/mymysql/godrv
 - go get github.com/go-sql-driver/mysql
 - go get labix.org/v2/mgo
 - mysql -e "CREATE DATABASE geminitest;"
 - mysql -u root -e "GRANT ALL ON geminitest.* TO geminitest@localhost IDENTIFIED BY 'geminitest'"
 - psql -c "CREATE DATABASE geminitest;" -U postgres
 - psql -c "CREATE USER "geminitest" WITH SUPERUSER PASSWORD 'geminitest';" -U postgres
 
script:
 - go test -v ./... -cover
 
notifications:
  webhooks:
    urls:
      - http://104.236.67.205:18009/travisci
