language: go
go:
  - 1.1
  - tip

services:
 - mysql
 - postgres
 - sqlite3
 - mongodb

before_script:
 - go get github.com/lib/pq
 - go get github.com/mattn/go-sqlite3
 - go get github.com/ziutek/mymysql/godrv
 - go get github.com/go-sql-driver/mysql
 - go get labix.org/v2/mgo